Json format
Web-networks/CodeGen pull request #1
Opened 2020-02-24 19:02 UTC by KatarinaAet

Json format for code generation process.

2020-02-24 19:52 UTC, NikitaSikalov requested changes

2020-02-24 19:52 UTC, NikitaSikalov commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
`activation` - это не тип значения json. Полагаю это строка из некоторого набора строк. Не увидел нигде описания в этом файле, какие строки могут быть в качестве `activation`. Нужно четко выписать этот массив.
Аналагично это касается и других параметров, таких как `regularizer `, `initializers `. 
https://www.json.org/json-ru.html
![image](https://user-images.githubusercontent.com/26010836/75185978-163c2380-5758-11ea-98a3-c2ee7c1b27f3.png)

2020-02-24 21:22 UTC, salamantos commented on json-input-format.md
> +where:
Я бы добавил переносы строк между пунктами для лучшей читаемости :)

2020-02-24 21:25 UTC, salamantos approved these changes

2020-02-24 21:34 UTC, m-malikov approved these changes

2020-02-24 22:25 UTC, demist commented
Для начала я бы предложил в будущем ограничивать круг reviewer‘ов теми, кто реально имеет отношение, иначе придётся долго собирать аппрувы. 
По самому реквесту — посмотрю чуть позже.

2020-02-25 01:45 UTC, nic11 commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
Я так полагаю, тут имеется в виду принадлежность некому enum'у

2020-02-25 01:50 UTC, nic11 approved these changes
В общем и целом, это практически ровно то же самое, что и было в гуглодоке, что есть и в доках кераса. Имхо, проще будет вносить конкретики уже не в этом md-шнике, а в yaml-ах для сваггера - они заодно будут служить реферансами, на которые будут смотреть остальные и мы сами при кодогенерации (в идеале).

А так ок, как примерная схема все выглядит хорошо

2020-02-25 07:39 UTC, NikitaSikalov commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
Я так и поняло, просто этот enum нужно тоже сразу описать

2020-02-25 14:12 UTC, sunruslan approved these changes

2020-02-25 21:21 UTC, demist reviewed
нужно дописать в файл все варианты значений для параметров, которые выбираются из ограниченного набора "строк"

2020-02-25 21:21 UTC, demist commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
++ нужно сразу описать варианты значений, т.к. меняться они не будут, и посылать их с фронта на бек строками большого смысла не имеет - можно обойтись просто id'шниками

да и в целом так будет правильнее

2020-02-26 19:40 UTC, nic11 commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
> можно обойтись просто id'шниками
Ненене, мое имхо - любые чрезмерные оптимизации - это очень плохо на начальной стадии: мы очень много будем смотреть на эти самые жсоны, не хватало еще путаться, что такое id=1, а что - id=7, чем они отличаются и т.д. и т.п.

2020-02-26 20:52 UTC, demist commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
Да, я не против сначала посылать просто строками. 
Про idшники - это было именно "можно", а не "нужно". 

Ключевой тезис в том, что наборы значений конечны и фиксированы, так что лучше их и в json-формате фиксировать

2020-02-26 21:37 UTC, nic11 commented on json-input-format.md
> +***activation***: Activation function to use (see activations). If you don't specify anything, no activation is applied (ie. "linear" activation: a(x) = x).
Зафиксируем :)
https://github.com/Web-networks/schemas/pull/1

2020-03-05 12:59 UTC, nic11 commented
Пока так замержу, а то долго висит. Если что можно issue открыть например

2020-03-05 12:59 UTC, merged